### ISSUE TITLE
Use the function name provided in serverless.yaml

### ISSUE THREAD

**Issue by delprofundo** [SC5/aws-serverless-hackathon-backend#5]
Hello,

I'm trying to test against my live service using this tool. It appears as though the names are generated internally and not using the serverless.yaml function name parameter.

for example my serverless functions are declared as such:

```  
echoMember:
    handler: handler.echo
    name: ${ self:provider.stage}-${self:custom.grub}-echo
    description: a simple payload echo POST test
    events:
    - http:
        path: /echo
        method: post
        cors: true
```

however the error provided when running the tests says its looking for the following name:

` arn:aws:lambda:us-east-1:774406369811:function:member-service-dev-pingMember`

is there a way to set the format of the names in the variables?
